name: Test Push Bot

on:
  workflow_dispatch:

jobs:
  push-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create test file
        run: |
          echo "Push test $(date)" > .push_test.txt

      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "Petfix Bot"
          git config user.email "bot@petfix.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add .push_test.txt
          git commit -m "✅ Push test from GitHub Actions"
          git push origin HEAD:main
